nodejs:
  devmemoryLimits: 2048Mi
  devmemoryRequests: 1024Mi
  devcpuRequests: 300m
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    OAUTH_CLIENT_REDIRECT: https://${SERVICE_FQDN}/
  keyVaults:
    fact:
      resourceGroup: fact
      secrets:
        - user-lock-timeout
        - oauth-client-secret
        - redis-access-key
        - AppInsightsInstrumentationKey-ai
        - csrf-token-secret
        - launchdarkly-sdk-key
        - storage-account-connection-string
        - storage-account-name
        - storage-account-primary-key
idam-pr:
  enabled: false
  redirect_uris:
    fact_admin:
      - https://${SERVICE_FQDN}/
