services:
  frontend:
    url: FRONTEND_URL
  api:
    url: FACT_API_URL
  idam:
    authorizationURL: IDAM_WEB_URL
    tokenURL: IDAM_API_URL
    addNewUserURL: IDAM_ADD_USER_URL
    clientID: OAUTH_CLIENT_ID
    clientSecret: OAUTH_CLIENT_SECRET
    callbackURL: OAUTH_CLIENT_REDIRECT
port: PORT
session:
  redis:
    host: REDIS_HOST
appInsights:
  instrumentationKey: APPINSIGHTS_KEY
csrf:
  tokenSecret: CSRF_TOKEN_SECRET
launchDarkly:
  sdkKey: LAUNCHDARKLY_SDK_KEY
