services:
  frontend:
    url: FRONTEND_URL
  api:
    url: FACT_API_URL
  idam:
    authorizationURL: IDAM_WEB_URL
    sessionURL: IDAM_SESSION_URL
    clientID: OAUTH_CLIENT_ID
    clientSecret: OAUTH_CLIENT_SECRET
    baseURL: BASE_URL
    idamUserDashboardURL : IDAM_USER_DASHBOARD_URL
  image-store:
    url: IMAGE_BASE_URL
    account-name: STORAGE_ACCOUNT_NAME
    account-key: STORAGE_ACCOUNT_PRIMARY_KEY
port: PORT
session:
  redis:
    host: REDIS_HOST
  secure-flag: SECURE_FLAG
appInsights:
  instrumentationKey: APPINSIGHTS_KEY
csrf:
  tokenSecret: CSRF_TOKEN_SECRET
launchDarkly:
  sdkKey: LAUNCHDARKLY_SDK_KEY
  ldUser: "fact-admin"
lock:
  timeout: USER_LOCK_TIMEOUT
storageAccountConnectionString: STORAGE_ACCOUNT_CONNECTION_STRING
