services:
  frontend:
    url: FRONTEND_URL
  api:
    url: FACT_API_URL
  idam:
    authorizationURL: IDAM_WEB_URL
    tokenURL: IDAM_API_URL
    clientID: OAUTH_CLIENT_ID
    clientSecret: OAUTH_CLIENT_SECRET
    callbackURL: OAUTH_CLIENT_REDIRECT
  image-store:
    url: IMAGE_BASE_URL
    account-name: ACCOUNT_NAME
    account-key: ACCOUNT_KEY
port: PORT
session:
  redis:
    host: REDIS_HOST
appInsights:
  instrumentationKey: APPINSIGHTS_KEY
csrf:
  tokenSecret: CSRF_TOKEN_SECRET
launchDarkly:
  sdkKey: LAUNCHDARKLY_SDK_KEY
storageAccountConnectionString: STORAGE_ACCOUNT_CONNECTION_STRING
