services:
  api:
    url: FACT_API_URL
  idam:
    authorizationURL: IDAM_WEB_URL
    tokenURL: IDAM_API_URL
    clientID: OAUTH_CLIENT_ID
    clientSecret: OAUTH_CLIENT_SECRET
    callbackURL: OAUTH_CLIENT_REDIRECT
port: PORT
session:
  redis:
    host: REDIS_HOST
appInsights:
  instrumentationKey: APPINSIGHTS_KEY
