services:
  frontend:
    url: FRONTEND_URL
  api:
    url: FACT_API_URL
  idam:
    authorizationURL: IDAM_WEB_URL
    tokenURL: IDAM_API_URL
    sessionURL: IDAM_SESSION_URL
    clientID: OAUTH_CLIENT_ID
    clientSecret: OAUTH_CLIENT_SECRET
    callbackURL: OAUTH_CLIENT_REDIRECT
    idamUserDashboardURL : IDAM_USER_DASHBOARD_URL
  image-store:
    url: IMAGE_BASE_URL
    account-name: STORAGE_ACCOUNT_NAME
    account-key: STORAGE_ACCOUNT_PRIMARY_KEY
port: PORT
session:
  redis:
    host: REDIS_HOST
appInsights:
  instrumentationKey: APPINSIGHTS_KEY
csrf:
  tokenSecret: CSRF_TOKEN_SECRET
launchDarkly:
  sdkKey: LAUNCHDARKLY_SDK_KEY
  ldUser: LAUNCHDARKLY_LD_USER
storageAccountConnectionString: STORAGE_ACCOUNT_CONNECTION_STRING
