security:
  referrerPolicy: 'origin'
port: 3300
services:
  frontend:
    url: 'http://localhost:3100'
  api:
    url: 'http://localhost:8080'
  idam:
    authorizationURL: 'https://idam-web-public.aat.platform.hmcts.net/login'
    tokenURL: 'https://idam-api.aat.platform.hmcts.net/o/token'
    sessionURL: 'https://idam-api.aat.platform.hmcts.net/session'
    addNewUserURL: 'https://idam-api.aat.platform.hmcts.net/api/v1/users/registration'
    clientID: 'fact_admin'
    clientSecret: 'get from AAT vault'
    callbackURL: 'http://localhost:3300/oauth2/callback'
  image-store:
    url: 'https://factaat.blob.core.windows.net/images/'
    account-name:
    account-key:
health:
  timeout: 5000
  deadline: 15000
session:
  secret: 'local'
  redis:
    host:
    key:
appInsights:
  instrumentationKey:
csrf:
  tokenSecret: 'get from AAT vault'
launchdarkly:
  sdkKey:
