security:
  referrerPolicy: 'origin'
port: 3300
services:
  frontend:
    url: 'http://localhost:3100'
  api:
    url: 'http://localhost:8080'
  idam:
    authorizationURL: 'https://idam-web-public.aat.platform.hmcts.net/o'
    sessionURL: 'https://idam-api.aat.platform.hmcts.net/session'
    apiURL: 'https://idam-api.aat.platform.hmcts.net'
    clientID: 'fact_admin'
    clientSecret: 'get from AAT vault'
    baseURL: 'http://localhost:3300'
    idamUserDashboardURL : 'https://idam-user-dashboard.aat.platform.hmcts.net'
  image-store:
    url: 'https://factaat.blob.core.windows.net/images'
    account-name:
    account-key:
health:
  timeout: 5000
  deadline: 15000
session:
  secret: 'LONG_RANDOM_STRING'
  secure-flag: false
  redis:
    host:
    key:
appInsights:
  instrumentationKey:
csrf:
  tokenSecret: 'get from AAT vault'
lock:
  timeout: 1
launchDarkly:
  sdkKey:
  ldUser: 'fact-admin'
flags:   # add feature-flag overrides below
