security:
  referrerPolicy: 'origin'
port: 3300
services:
  api:
    url: 'http://localhost:8080'
  idam:
    authorizationURL: 'https://idam-web-public.aat.platform.hmcts.net/login'
    tokenURL: 'https://idam-api.aat.platform.hmcts.net/o/token'
    clientID: 'fact_admin'
    clientSecret: 'fact_admin_secret'
    callbackURL: 'http://localhost:3300/oauth2/callback'
health:
  timeout: 5000
  deadline: 15000
session:
  secret: 'local'
  redis:
    host:
    key:
